[tool.isort]
profile = "black"

[tool.black]
target-version = ['py37']
line-length = 100
include = '(pipeline|tests)/'

[tool.pylint]

	[tool.pylint.FORMAT]
	max-line-length = 100

	[tool.pylint.'MESSAGE CONTROL']
	disable = ["all"]
	enable = [
		"F",
		"E",
		"unreachable",
		"duplicate-key",
		"unnecessary-semicolon",
		"global-variable-not-assigned",
		"unused-variable",
		"binary-op-exception",
		"bad-format-string",
		"anomalous-backslash-in-string",
		"bad-open-mode",
	]

[tool.pyright]
pythonVersion = "3.7"
typeCheckingMode = "basic"
reportMissingTypeStubs = false
exclude=["*"]
include=["pipeline", "tests"]

[tool.mypy]
python_version = "3.7"
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true
